version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER} # nteasocial
      POSTGRES_PASSWORD: ${DB_PASSWORD} # pass
      POSTGRES_DB: ${DB_DATABASE} # grocery_db
    ports:
      - "${DB_PORT}:5432" # 5432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  app:
    build: .
    depends_on:
      - db
    ports:
      - "${PORT}:8001" # 8001:8001
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: npm start
